function [fitresult, gof] = fit_linear(x, y)
%CREATEFIT(LOGX,LOGY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: logx
%      Y Output: logy
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-May-2022 09:04:35


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'logy vs. logx', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'logx', 'Interpreter', 'none' );
% ylabel( 'logy', 'Interpreter', 'none' );
% grid on


