function [fitresult, gof,output] = fit_linear(x, y,poids,modele_ponderation, modele_robuste)
%CREATEFIT(LOGX,LOGY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: logx
%      Y Output: logy
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-May-2022 09:04:35




%%

% si pas de vecteur poids donné, la boucle suivante le met par défaut à un
if modele_ponderation == 'non'
    poids = ones(length(y),1);
end

%% Fit: 'untitled fit 1'.
[xData, yData, weights] = prepareCurveData( x, y, poids );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', ['LinearLeastSquares'] );
opts.Robust = modele_robuste;
opts.Weights = weights;


% Fit model to data.
[fitresult, gof,output] = fit( xData, yData, ft,opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'logy vs. logx', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
% xlabel( 'logx', 'Interpreter', 'none' );
% ylabel( 'logy', 'Interpreter', 'none' );
% grid on


