function [fitresult, gof] = createFit1_minimisation_uvp(x1l, y1l,plot_figure,fit_type,x2,y2,fit_type2)
%CREATEFIT1(X1L,Y1L)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x1l
%      Y Output: y1l
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Oct-2017 14:55:45


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x1l, y1l );

% Set up fittype and options.
% ft = fittype( 'poly6' );
ft = fittype( fit_type );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

%% Fit: 'untitled fit 1'.
[xData2, yData2] = prepareCurveData( x2, y2 );

% Set up fittype and options.
% ft = fittype( 'poly6' );
ft = fittype( fit_type2 );

% Fit model to data.
[fitresult2, gof2] = fit( xData2, yData2, ft );

if plot_figure == 1
    figure( 'Name', 'untitled fit 1' );
    subplot(1,2,1)
    h = plot( fitresult, xData, yData );
    legend( h, 'ref', fit_type, 'Location', 'NorthEast' );
    
    subplot(1,2,2)
    h = plot( fitresult2, xData2, yData2 );
    legend( h, 'to adj', fit_type2, 'Location', 'NorthEast' );
    grid on
end


