function [pathfilename] = CreateCTDfile(project_folder)
%CreateCTDfile Write a CTD file in the CTD folder of a project with
%information from the vector
%
%
% inputs :
%   project_folder : full path of the project
%
% output :
%   pathfilename : full path to the new CTD file
%

column_names = ["Pressure in Water Column [db] 	Depth [salt water, m] 	"...
    "QC Flag 	Angular scattering coef at 117° 470 nm [m-1 Sr-1] 	"...
    "Bbp470 [m-1] 	Beam Transmission 660 nm [%] 	"...
    "Beam attenuation coef 660 nm [m-1] 	Chloro Fluo [mg Chl/m3] 	"...
    "Conductivity [mS/cm] 	Cpar [%] 	"...
    "Fcdom factory [ppb QSE] 	In situ Density Anomaly [kg/m3] 	"...
    "Nitrate ISUS [µMol/L] 	Oxygen  [ml/l] 	"...
    "Oxygen  [umol/Kg] 	Oxygen Per Sat [µmol/Kg] 	"...
    "Oxygen [ml/l] 	PAR [µmol m-2 s-1] 	"...
    "PAR ratio [%] 	Part backscattering coef 470 nm [m-1] 	"...
    "Ph 	Potential Temperature [degC] 	"...
    "Practical Salinity [psu] 	SPAR [µmol m-2 s-1] 	"...
    "Temperature [degC] 	Time [second]"];

end